# Set the maximum line length to 79.
line-length = 79
ignore = ["E501"]
exclude = [".venv", "migrations"]

[lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
select = ["E", "F", "I"]

[format]
# Prefer single quotes over double quotes.
quote-style = "single"
